#!/bin/bash
# silly script that makes qimpp, runs it on HelloWorld.java, then compiles out.cc
set -e
make
java qimpp/QimppTranslator testfiles/HelloWorld.java
cd testfiles
g++ java_lang.cc out.cc
cd ..
echo "out.cc compiled correctly!!!"
